# -*- coding: utf-8 -*-
"""super_market.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rk_Eri6_acO4i_58xEbxHUl7BNF7PVTb
"""

# Importando bibliotecas
import pandas as pd
from sqlite3.dbapi2 import connect
import sqlite3
import csv
import os

# criando banco de dados
conection = sqlite3.connect('super_market.db')

# Conectando ao banco de dados
cursor = conection.cursor()

# Salvando o banco de dados
conection.commit()

# Desconectando o Banco de dados
conection.close()

# consultar nome das tabelas
result = cursor.execute("select name from sqlite_master")
result.fetchall()

# Caminho para o CSV
csv_path = '/content/products_supermarket.csv'

with open(csv_path, newline='', encoding='utf-8') as csvfile:

    reader = csv.DictReader(csvfile)

    original_columns = reader.fieldnames
    cleaned_column_names = [col.strip().replace(" ", "_") for col in original_columns]
    escaped_column_names = [f"`{col}`" for col in cleaned_column_names]

    sql_columns = ', '.join([f"{col} TEXT" for col in escaped_column_names])
    cursor.execute(f"CREATE TABLE Products ({sql_columns})")

    for row in reader:
        cleaned_row = {col.strip().replace(" ", "_"): value for col, value in row.items()}
        placeholders = ', '.join([f":{col}" for col in cleaned_column_names])
        column_list_sql = ', '.join(escaped_column_names)

        sql_insert = f"INSERT INTO Products ({column_list_sql}) VALUES ({placeholders})"
        cursor.execute(sql_insert, cleaned_row)

# buscar todos os registros
cursor.execute("SELECT * FROM Products")
print(cursor.fetchall())

cursor.execute("PRAGMA table_info(Products)")
colunas = cursor.fetchall()

# Mostra só os nomes das colunas
nomes_colunas = [coluna[1] for coluna in colunas]
print(nomes_colunas)

cursor.execute("SELECT * FROM Products")

# Transforma os dados em uma lista de tuplas
products_market = cursor.fetchall()

# Conta o total de registros
total = len(products_market)

# Imprime o total
print("Total de produtos:", total)